INSERT INTO BANK_ADMIN.CUSTOMER (CUS_ID, CUSTOMER_NAME, EMAIL, ADDRESS, ACCOUNT_ID)
VALUES (1, 'Janani', 'janani.v@hcl.com', '5b,mtp', 1);




INSERT INTO BANK_ADMIN.CUSTOMER (CUS_ID, CUSTOMER_NAME, EMAIL, ADDRESS, ACCOUNT_ID)
VALUES (2, 'Jaanu', 'jaanu.v@hcl.com', '5a,mtp', 2);




INSERT INTO BANK_ADMIN.CUSTOMER (CUS_ID, CUSTOMER_NAME, EMAIL, ADDRESS, ACCOUNT_ID)
VALUES (3, 'Sowmiya', 'somwiya@hcl.com','5c,mtp',3);




INSERT INTO BANK_ADMIN.CUSTOMER (CUS_ID, CUSTOMER_NAME, EMAIL, ADDRESS, ACCOUNT_ID)
VALUES (4, 'Sowmi', 'sowmi@hcl.com','5d,mtp', 4);


INSERT INTO BANK_ADMIN.ACCOUNT (ACCOUNT_ID, ACCOUNT_NUMBER, BALANCE, CUS_ID)
VALUES (1, 'HCL1234567890', '100000000',1);



INSERT INTO BANK_ADMIN.ACCOUNT (ACCOUNT_ID, ACCOUNT_NUMBER, BALANCE, CUS_ID)
VALUES (2, 'HCL1234567891', '1000',2);



INSERT INTO BANK_ADMIN.ACCOUNT (ACCOUNT_ID, ACCOUNT_NUMBER, BALANCE, CUS_ID)
VALUES (3, 'HCL1234567892', '100000000',3);



INSERT INTO BANK_ADMIN.ACCOUNT (ACCOUNT_ID, ACCOUNT_NUMBER, BALANCE, CUS_ID)
VALUES (4, 'HCL1234567894', '560',4);



